name: Contracts CI/CD
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Cache yarn modules
      uses: actions/cache@v2
      with:
        path: ~/.yarn
        key: yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: 
          yarn-${{ hashFiles('yarn.lock') }}
          yarn-

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build contracts
      run: yarn build:contracts

    - name: Run coverage
      run: yarn coverage

    - name: Upload report
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  deploy-rinkeby:
    runs-on: ubuntu-latest
    needs: test
    env:
      CD: true
      ETH_KEY: ${{ secrets.ETH_KEY }}
      ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
      REGISTRY_RINKEBY: "0x0cd3621EC403F26ad9F79c3d77B1dda1f8474c6f"
    steps:
    - uses: actions/checkout@v1

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Cache yarn modules
      uses: actions/cache@v2
      with:
        path: ~/.yarn
        key: yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          yarn-${{ hashFiles('yarn.lock') }}
          yarn-

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    # - name: Deploy Factory
    #   run: cd packages/govern-create && yarn deploy-factory --network rinkeby

    # - name: Deploy Govern
    #   run: cd packages/govern-create && yarn deploy-govern --network rinkeby > github-message

    # - name: Log
    #   run: cat packages/govern-create/github-message
