name: Contracts CI/CD
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.5

      - name: Cache yarn modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: yarn-${{ hashFiles('yarn.lock') }}

      - name: Cache contracts
        uses: actions/cache@v2
        with:
          path: |
            packages/*/cache
            packages/*/artifacts
            ~/.cache/buidler-nodejs/
            ~/.cache/hardhat-nodejs/
          key: contracts-${{ hashFiles('packages/*/contracts/**/*.sol') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build contracts
        run: yarn compile:cached

      - name: Run coverage
        run: yarn coverage

      - name: Upload report
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
