name: Govern CI/CD
on: 
  push:
    paths:
    - 'packages/govern/**'
    branches:
    - master
    - dao
    
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Cache yarn modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: yarn-${{ hashFiles('yarn.lock') }}

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run all govern tests
      run: cd packages/govern && yarn test

