name: Govern-Console CI/CD
on:
  push:
    paths:
    - 'packages/govern-console/**'
    

jobs:
  build-and-deploy-console:
    runs-on: ubuntu-latest
    container: fleek/create-react-app:node-15
    name: builds and deploys console
    steps:
      - uses: actions/checkout@v2
      - name: activate rinkeby's fleek
        run: mv fleek/console.rinkeby.json .fleek.json
        working-directory: packages/govern-console
        if: github.ref == 'refs/heads/develop'
      - name: activate mainnet's fleek
        run: mv fleek/console.mainnet.json .fleek.json
        working-directory: packages/govern-console
        if: github.ref == 'refs/heads/master'
      - name: builds and deploys console
        id: deploy
        uses: fleekhq/action-deploy@v1
        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}
          workDir: packages/govern-console

  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    container: fleek/create-react-app:node-15
    name: builds and deploys storybook
    steps:
      - uses: actions/checkout@v2
      - name: activate rinkeby's fleek
        run: mv fleek/storybook.json .fleek.json
        working-directory: packages/govern-console
        if: github.ref == 'refs/heads/develop'
      - name: builds and deploys storybook
        id: deploy
        uses: fleekhq/action-deploy@v1
        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}
          workDir: packages/govern-console

  

