name: Server CI/CD
on:
  push:
    branches:
    - master
    tags:
    - v*
env:
  # This is a base repository and we use git refs to set the version of the container
  # ${GITHUB_REF##*/} will be either a branch name or a tag depending on the event
  REPO: aragon/govern-server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_TOKEN}}
    - run: .github/scripts/docker-build.sh . $REPO ${GITHUB_SHA}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - run: docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_TOKEN}}
    - run: .github/scripts/docker-release.sh $REPO:${GITHUB_SHA} $REPO:${GITHUB_REF##*/}
    - run: .github/scripts/docker-release.sh $REPO:${GITHUB_SHA} $REPO:latest

  deploy-rinkeby:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: release
    steps:
    - uses: actions/checkout@v2
    - run: .github/scripts/kubectl-config.sh ${{secrets.KUBE_CA}} ${{secrets.KUBE_SERVER}} ${{secrets.KUBE_TOKEN}}
    - run: .github/scripts/kubectl-set-image.sh govern-server-rinkeby $REPO:${GITHUB_REF##*/}
    - run: .github/scripts/kubectl-wait-ready.sh govern-server-rinkeby
    # wait 10 sec for k8s to reroute ingress and check the endpoint
    - run: sleep 10 && curl --fail https://govern-rinkeby.backend.aragon.org -H accept:text/html

  deploy-mainnet:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: release
    steps:
    - uses: actions/checkout@v2
    - run: .github/scripts/kubectl-config.sh ${{secrets.KUBE_CA}} ${{secrets.KUBE_SERVER}} ${{secrets.KUBE_TOKEN}}
    - run: .github/scripts/kubectl-set-image.sh govern-server $REPO:${GITHUB_REF##*/}
    - run: .github/scripts/kubectl-wait-ready.sh govern-server
    # wait 10 sec for k8s to reroute ingress and check the endpoint
    - run: sleep 10 && curl --fail https://govern.backend.aragon.org -H accept:text/html
